[build-system]
requires = [
    "setuptools >= 40.0.4",
    "setuptools_scm >= 2.0.0, <4",
    "setuptools_scm_git_archive",
    "wheel >= 0.29.0",
    "Cython >= 0.25.2",
]
build-backend = 'setuptools.build_meta'
